language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t lukeabc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lukeabc/docker-react npm run test -- --coverage
