FROM node:alpine


#next two linesneeded in VM for some reason
USER node
RUN mkdir /home/node/app


WORKDIR '/home/node/app'

COPY --chown=node:node package.json .

RUN npm install

COPY --chown=node:node . .

CMD ["npm","run","start"]
